name: missa_maa_oon
description: Tallenna nykyinen sijaintisi. Save your current location.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.4.0+1

_author: Arttu Ylhävuori

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  about: ^2.1.3
  cupertino_icons: ^1.0.6
  geolocator: ^10.1.0
  intl: ^0.18.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  isar_generator: ^3.1.0+1
  pubspec_extract: ^2.0.5

flutter:
  uses-material-design: true
  assets:
    - LICENSE.md
    - README.md
    - assets/icon.png
    - assets/source-icon.png

flutter_icons:
  android: false
  ios: true
  image_path: 'assets/source-icon.png'
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: true
